#include <stdio.h>
#include <stdlib.h>
#include <utils.h>
/*
  Fisher-Yates Shuffle Algorithm
 
  A random permutation is generated by swapping each element with a
  randomly chosen element from the unshuffled portion of the array.
  The permutation is then applied, inverted, and reversed to restore
  the original order.
 */

// Generates a random permutation of indices [0, n-1].
void generate_permutation(size_t *perm, size_t n) {
    for (size_t i = 0; i < n; i++) {
        perm[i] = i;
    }

    for (size_t i = n - 1; i > 0; i--) {
        size_t j = rand() % (i + 1);
        size_t temp = perm[i];
        perm[i] = perm[j];
        perm[j] = temp;
    }
}

// Applies permutation: shuffled[i] = input[perm[i]]
void apply_permutation(const char *input, char *shuffled, size_t *perm, size_t n) {
    for (size_t i = 0; i < n; i++) {
        shuffled[i] = input[perm[i]];
    }
}

// Computes inverse: if perm[i] = j then inv_perm[j] = i
void invert_permutation(size_t *perm, size_t *inv_perm, size_t n) {
    for (size_t i = 0; i < n; i++) {
        inv_perm[perm[i]] = i;
    }
}


// Restores original: original[i] = shuffled[inv_perm[i]] 
void reverse_permutation(const char *shuffled, char *original, size_t *inv_perm, size_t n) {
    for (size_t i = 0; i < n; i++) {
        original[i] = shuffled[inv_perm[i]];
    }
}